webtalk_init -webtalk_dir D:\\Kishore_Sir_Project\\imageProcSystem\\imageProcSystem.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2024-04-08 02:56:03" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "p9k8856m71lu6a1e5m6b0be1n6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_15" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "14.877 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1712265684608" -context "sdk\\\\hardware/1712265684608"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1712265684608"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1712265684608"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1712265684608"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1712265684608"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1712265684608"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1712265684608"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1712265684608"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1712265684608"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1712265684608"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1712265684608"
webtalk_add_data -client sdk -key uid -value "1712265752272" -context "sdk\\\\bsp/1712265752272"
webtalk_add_data -client sdk -key hwid -value "1712265684608" -context "sdk\\\\bsp/1712265752272"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1712265752272"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1712265752272"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1712265752272"
webtalk_add_data -client sdk -key uid -value "1712265755137" -context "sdk\\\\application/1712265755137"
webtalk_add_data -client sdk -key hwid -value "1712265684608" -context "sdk\\\\application/1712265755137"
webtalk_add_data -client sdk -key bspid -value "1712265752272" -context "sdk\\\\application/1712265755137"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1712265755137"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1712265755137"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1712265755137"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1712265755137"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1712265755137"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1712265755137"
webtalk_add_data -client sdk -key projSize -value "688.86328125" -context "sdk\\\\application/1712265755137"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1712525163458"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1712525163458"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1712525163458"
webtalk_add_data -client sdk -key DebugCount -value "11" -context "sdk\\\\bsp/1712525163458"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1712525163458"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1712525163458"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1712525163458"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1712525163458"
webtalk_transmit -clientid 3207810745 -regid "" -xml D:\\Kishore_Sir_Project\\imageProcSystem\\imageProcSystem.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\Kishore_Sir_Project\\imageProcSystem\\imageProcSystem.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\Kishore_Sir_Project\\imageProcSystem\\imageProcSystem.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
