# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/imageProcSystem/imageProcSystem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcSystem || ORIG_REF_NAME==imageProcSystem} -quiet] -quiet

# IP: bd/imageProcSystem/ip/imageProcSystem_processing_system7_0_0/imageProcSystem_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcSystem_processing_system7_0_0 || ORIG_REF_NAME==imageProcSystem_processing_system7_0_0} -quiet] -quiet

# IP: bd/imageProcSystem/ip/imageProcSystem_axi_dma_0_0/imageProcSystem_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcSystem_axi_dma_0_0 || ORIG_REF_NAME==imageProcSystem_axi_dma_0_0} -quiet] -quiet

# IP: bd/imageProcSystem/ip/imageProcSystem_imageProc_0_0/imageProcSystem_imageProc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcSystem_imageProc_0_0 || ORIG_REF_NAME==imageProcSystem_imageProc_0_0} -quiet] -quiet

# IP: bd/imageProcSystem/ip/imageProcSystem_ps7_0_axi_periph_0/imageProcSystem_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcSystem_ps7_0_axi_periph_0 || ORIG_REF_NAME==imageProcSystem_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/imageProcSystem/ip/imageProcSystem_rst_ps7_0_100M_0/imageProcSystem_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcSystem_rst_ps7_0_100M_0 || ORIG_REF_NAME==imageProcSystem_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/imageProcSystem/ip/imageProcSystem_axis_dwidth_converter_0_0/imageProcSystem_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcSystem_axis_dwidth_converter_0_0 || ORIG_REF_NAME==imageProcSystem_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/imageProcSystem/ip/imageProcSystem_axi_smc_0/imageProcSystem_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcSystem_axi_smc_0 || ORIG_REF_NAME==imageProcSystem_axi_smc_0} -quiet] -quiet

# IP: bd/imageProcSystem/ip/imageProcSystem_xlconcat_0_0/imageProcSystem_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcSystem_xlconcat_0_0 || ORIG_REF_NAME==imageProcSystem_xlconcat_0_0} -quiet] -quiet

# IP: bd/imageProcSystem/ip/imageProcSystem_system_ila_0_0/imageProcSystem_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcSystem_system_ila_0_0 || ORIG_REF_NAME==imageProcSystem_system_ila_0_0} -quiet] -quiet

# IP: bd/imageProcSystem/ip/imageProcSystem_auto_pc_0/imageProcSystem_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcSystem_auto_pc_0 || ORIG_REF_NAME==imageProcSystem_auto_pc_0} -quiet] -quiet

# XDC: bd/imageProcSystem/imageProcSystem_ooc.xdc
