# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Kishore_Sir_Project/imageProcSystem/imageProcSystem.srcs/sources_1/bd/imageProcSystem/ip/imageProcSystem_imageProc_0_0/imageProcSystem_imageProc_0_0.xci
# IP: The module: 'imageProcSystem_imageProc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Kishore_Sir_Project/imageProcSystem/imageProcSystem.srcs/Kishore_Sir_Project/IP_repo/imageProc/imageProc.srcs/sources_1/ip/outputBuffer/outputBuffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] -quiet

# XDC: d:/Kishore_Sir_Project/imageProcSystem/imageProcSystem.srcs/Kishore_Sir_Project/IP_repo/imageProc/imageProc.srcs/sources_1/ip/outputBuffer/outputBuffer.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: d:/Kishore_Sir_Project/imageProcSystem/imageProcSystem.srcs/sources_1/bd/imageProcSystem/ip/imageProcSystem_imageProc_0_0/imageProcSystem_imageProc_0_0.xci
# IP: The module: 'imageProcSystem_imageProc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Kishore_Sir_Project/imageProcSystem/imageProcSystem.srcs/Kishore_Sir_Project/IP_repo/imageProc/imageProc.srcs/sources_1/ip/outputBuffer/outputBuffer.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] -quiet

# XDC: d:/Kishore_Sir_Project/imageProcSystem/imageProcSystem.srcs/Kishore_Sir_Project/IP_repo/imageProc/imageProc.srcs/sources_1/ip/outputBuffer/outputBuffer.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
